language: ruby
cache: bundler
rvm:
- 2.0.0
env:
  secure: gB53f/Ne9x8mBFxm5BfSebnjkTl1/QynH8Gt9jNVFBgiqDmW/MMDj2UmmQ3TZrkpEIjNH9+p2G6U8ZiC+kzWyuYaoiacSW9+p1ZIkoKLHw22HQe3mproz/V0a8h8d5B+3aMJGWG83VMVnv63bgGWimOjgC1HvGTS86KpgLKs10A=
